import pandas as pd

# loading data from a CSV file and handling errors
def load_data(file_path):
    try:
        df = pd.read_csv(file_path)
        print("CSV data loaded successfully")
        return df
    except Exception as e:
        print(f"Error loading CSV file: {e}")
        return None

# ensure correct data types are present
def prepare_data(df):
    df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
    df['total_revenue'] = df['product_price'] * df['quantity']
    return df

# task 1- computing the total revenue generated by the online store for each month
def compute_monthly_revenue(df):
    df['month_year'] = df['order_date'].dt.to_period('M')
    monthly_revenue = df.groupby('month_year')['total_revenue'].sum().reset_index(name='total_revenue')
    return monthly_revenue

# task 2- compute the total revenue generated by each product
def compute_product_revenue(df):
    product_revenue = df.groupby('product_id')['total_revenue'].sum().reset_index()
    return product_revenue

# task 3- compute the total revenue generated by each customer
def compute_customer_revenue(df):
    customer_revenue = df.groupby('customer_id')['total_revenue'].sum().reset_index()
    return customer_revenue

# task 4- identify the top 10 customers by revenue generated
def top_10_customers_by_revenue(customer_revenue):
    top_customers = customer_revenue.sort_values(by='total_revenue', ascending=False).head(10)
    return top_customers

if __name__ == "__main__":
    # load data
    orders_df = load_data('orders.csv')
    if orders_df is not None:
        # prepare data
        orders_df = prepare_data(orders_df)
        
        # displaying the monthly revenue
        monthly_revenue = compute_monthly_revenue(orders_df)
        print("Monthly Revenue:")
        print(monthly_revenue)
        
        # displaying the product revenue
        product_revenue = compute_product_revenue(orders_df)
        print("\nProduct Revenue:")
        print(product_revenue)
        
        # displaying the customer revenue
        customer_revenue = compute_customer_revenue(orders_df)
        print("\nCustomer Revenue:")
        print(customer_revenue)
        
        # displaying the top 10 customers by revenue
        top_customers = top_10_customers_by_revenue(customer_revenue)
        print("\nTop 10 Customers by Revenue:")
        print(top_customers)
